# NumPy

Adithya Narayan 19BBS0068

Question 1: Create a 4X2 integer array and Prints its attributes
Note: element must be a type of unsigned int16. And print the following Attributes: –

The shape of an array.
Array dimensions.
The Length of each element of the array in bytes.

In [1]:
import numpy as np
a=list(range(0,8))
a=np.array(a,dtype='uint16').reshape(4,2)
#Shape of Array
a.shape

(4, 2)

In [2]:
#size of each element
a.itemsize

2

In [3]:
#data type of elements
a.dtype

dtype('uint16')

In [4]:
#number of dimensions of numpy array
a.ndim

2

Question 2: Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10

In [5]:
b=np.arange(100,200,10).reshape(5,2)
b

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

Question 3: Following is the provided numPy array. return array of items in the third column from all rows
import numpy
sampleArray = numpy.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
Expected Output:

Printing Input Array
[[11 22 33]
 [44 55 66]
 [77 88 99]]

 Printing array of items in the third column from all rows
[22 55 88]

In [6]:
sampleArray=np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
print(sampleArray)

[[11 22 33]
 [44 55 66]
 [77 88 99]]


In [7]:
#printing items of third column from every row
n=sampleArray[:,2:].reshape(1,3)
print(n)

[[33 66 99]]


In [8]:
#printing items of third column from every row
n=sampleArray[:,1:2].reshape(1,3)
print(n)

[[22 55 88]]


Question 4: Following is the given numpy array return array of odd rows and even columns
import numpy

sampleArray = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
Expected Output:

Printing Input Array
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]

 Printing array of odd rows and even columns
[[ 6 12]
 [30 36]
 [54 60]]

In [9]:
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]]) 
print(sampleArray)

[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]


In [10]:
n=sampleArray[::2,1::2]
print(n)

[[ 6 12]
 [30 36]
 [54 60]]


Question 5: Add the following two NumPy arrays and Modify a result array by calculating the square of each element
import numpy

arrayOne = numpy.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = numpy.array([[15 ,33, 24], [4 ,7, 1]])
Expected Output:

addition of two arrays is 

[[20 39 33]
 [25 25 28]]

Result array after calculating the square of all elements

[[ 400 1521 1089]
 [ 625  625  784]]

In [11]:
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]]) 
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])
arraysum=arrayOne+arrayTwo
print("addition of two arrays is")
print(arraysum)

addition of two arrays is
[[20 39 33]
 [25 25 28]]


In [12]:
arraysq=arraysum**2
print("Result array after calculating the square of all elements")
print(arraysq)

Result array after calculating the square of all elements
[[ 400 1521 1089]
 [ 625  625  784]]


Question 7; Sort following NumPy array
7.1- by the second row and
7.2-by the second column
import numpy
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
Expected Output:

Printing Original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]

Sorting Original array by secoond row
[[73 43 34]
 [12 22 82]
 [66 94 53]]

Sorting Original array by secoond column
[[82 22 12]
 [34 43 73]
 [53 94 66]]

In [13]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
print('Printing Original array',end=' ')
print(sampleArray)

Printing Original array [[34 43 73]
 [82 22 12]
 [53 94 66]]


In [14]:
sorted=sampleArray[:,sampleArray[1].argsort()]
print('Sorting Original array by second row',end=' ')
print(sorted)

Sorting Original array by second row [[73 43 34]
 [12 22 82]
 [66 94 53]]


In [15]:
sorted=sampleArray[sampleArray[:,1].argsort()]
print('Sorting Original array by second column',end=' ')
print(sorted)

Sorting Original array by second column [[82 22 12]
 [34 43 73]
 [53 94 66]]


# Pandas

Question 6: Find the most expensive car company name
Print most expensive car’s company name and price.

Expected Output:

Python Pandas printing most costly car name

In [28]:
import pandas as pd
data=pd.read_csv("C:\\Users\\User\\Desktop\\R Materials\\Auto_data.csv")
data[data['price']==data['price'].max()]['company']

35    mercedes-benz
Name: company, dtype: object

Question 7: Find each company’s Higesht price car

In [30]:
data.groupby('company').max()['price']

company
alfa-romero      16500.0
audi             18920.0
bmw              41315.0
chevrolet         6575.0
dodge             6377.0
honda            12945.0
isuzu             6785.0
jaguar           36000.0
mazda            18344.0
mercedes-benz    45400.0
mitsubishi        8189.0
nissan           13499.0
porsche          37028.0
toyota           15750.0
volkswagen        9995.0
volvo            13415.0
Name: price, dtype: float64

Question 8: Concatenate two data frames using the following conditions
Create two data frames using the following two Dicts, Concatenate those two data frames and create a key for each data frame.

GermanCars = {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'], 'Price': [23845, 171995, 135925 , 71400]}
japaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '], 'Price': [29995, 23600, 61500 , 58900]}


In [60]:
GermanCars=pd.DataFrame({'Company':['Ford', 'Mercedes', 'BMV', 'Audi'], 'Price': [23845, 171995, 135925 , 71400]},index=[1,2,3,4])
japaneseCars=pd.DataFrame({'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '], 'Price': [29995, 23600, 61500 , 58900]},index=[5,6,7,8])

In [61]:
GermanCars


Company   Price
1      Ford   23845
2  Mercedes  171995
3       BMV  135925
4      Audi   71400

In [62]:
japaneseCars

Company  Price
5       Toyota  29995
6        Honda  23600
7       Nissan  61500
8  Mitsubishi   58900

In [63]:
pd.concat([GermanCars,japaneseCars],axis=0)

Company   Price
1         Ford   23845
2     Mercedes  171995
3          BMV  135925
4         Audi   71400
5       Toyota   29995
6        Honda   23600
7       Nissan   61500
8  Mitsubishi    58900

Question 9: Sort all cars by Price column

In [76]:
data.sort_values(by='price')

index        company body-style  wheel-base  length engine-type  \
13     16      chevrolet  hatchback        88.4   141.1           l   
27     36          mazda  hatchback        93.1   159.1         ohc   
48     66         toyota  hatchback        95.7   158.7         ohc   
36     49     mitsubishi  hatchback        93.7   157.3         ohc   
28     37          mazda  hatchback        93.1   159.1         ohc   
..    ...            ...        ...         ...     ...         ...   
11     14            bmw      sedan       103.5   193.8         ohc   
35     47  mercedes-benz    hardtop       112.0   199.2        ohcv   
22     31          isuzu      sedan        94.5   155.9         ohc   
23     32          isuzu      sedan        94.5   155.9         ohc   
47     63        porsche  hatchback        98.4   175.7       dohcv   

   num-of-cylinders  horsepower  average-mileage    price  
13            three          48               47   5151.0  
27             four          68               30   5195.0  
48             four          62               35   5348.0  
36             four          68               37   5389.0  
28             four          68               31   6095.0  
..              ...         ...              ...      ...  
11              six         182               16  41315.0  
35            eight         184               14  45400.0  
22             four          70               38      NaN  
23             four          70               38      NaN  
47            eight         288               17      NaN  

[61 rows x 10 columns]

Question 10: Count total cars per company

In [69]:
data['company'].value_counts()

toyota           7
bmw              6
mazda            5
nissan           5
audi             4
volkswagen       4
mercedes-benz    4
mitsubishi       4
alfa-romero      3
honda            3
isuzu            3
porsche          3
chevrolet        3
jaguar           3
dodge            2
volvo            2
Name: company, dtype: int64